# This is a basic workflow to help you get started with Actions

name: SWE Fetch and Transform Data

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 9 * * 1" # Run every Monday at 9am UTC
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch_and_transform_data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Fetch and transform data
        run: |
          python etl_scripts/swe_fetch_transform_data.py
